
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS delivery_address;

DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS client;

DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS state;
DROP TABLE IF EXISTS country;

DROP TABLE IF EXISTS hibernate_sequences;
DROP SEQUENCE IF EXISTS hibernate_sequence;
DROP SEQUENCE IF EXISTS users_user_id_seq;

 